### PR TITLE
scala 2.13.15

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Review by raboof — APPROVED** [review]
LGTM - I wonder if at some point we should start moving these to Scala 3

**Comment by pjfanning** [comment]
> LGTM - I wonder if at some point we should start moving these to Scala 3

Sure. I just want to concentrate on getting them updated to Pekko 1.1 first but I look at Scala 3 soon.

**Comment by pjfanning** [comment]
> > LGTM - I wonder if at some point we should start moving these to Scala 3
> 
> Sure. I just want to concentrate on getting them updated to Pekko 1.1 first but I look at Scala 3 soon.

The download stats from repository.apache.org are often broken but when I do get to see them, Scala 3 is still trailing badly. Probably behind Scala 2.12 and well behind Scala 2.13.

**Comment by raboof** [comment]
> > LGTM - I wonder if at some point we should start moving these to Scala 3
> 
> I just want to concentrate on getting them updated to Pekko 1.1 first but I look at Scala 3 soon.

seems reasonable to me

> The download stats from repository.apache.org are often broken but when I do get to see them, Scala 3 is still trailing badly. Probably behind Scala 2.12 and well behind Scala 2.13.

that might be a chicken-and-egg thing though ;) - it would be good to have stats over the entire Scala ecosystem, but I'm not sure of any.

**Comment by pjfanning** [comment]
The August download stats are working. pekko-actor is fairly indicative of download trends.
pekko-actor_2.13 jars downloads: 277,000
pekko-actor_2.12 jars downloads: 159,000
pekko-actor_3 jars downloads: 56,000

**Comment by raboof** [comment]
That's pretty stark! Ofc it's hard to say whether this means Scala 3 adoption is slow in general, or that we're failing to appeal to the 'modern' Scala users. Assuming that's something we want, it might be good to be at least somewhat 'ahead of the curve' of our download stats - but indeed it's fine to wait a while still, I was not intending to suggest we move everything over right now ;)

**Comment by pjfanning** [comment]
The only other major set of Scala jar download stats that I have access to are for Jackson. Its Scala module is probably not indicative. A lot of its downloads are driven by frameworks like Spark and those Big Data frameworks do not yet support Scala 3. With jackson-module-scala, Scaal 2.12 still slightly outperforms Scala 2.13. Scala 2.11 downloads are about 1/10th of the 2.12 ones. Scala 3 downloads are about 1/50th of the 2.12 ones. Scala 2.10 downloads are about 1/100th of the 2.12 ones.

**Pull request merged**
